<!DOCTYPE html>
<html>
<head>
	<title>ChroncileX Explorer</title>
	<!-- HTTP Client Library -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js" integrity="sha256-mpnrJ5DpEZZkwkE1ZgkEQQJW/46CSEh/STrZKOB/qoM=" crossorigin="anonymous"></script>
	<!-- VueJS -->
	<script src="https://cdn.jsdelivr.net/npm/vue@2.6.6/dist/vue.js" integrity="sha384-bNxnjzgkQ1TIrVCdltvL1vdzkGeB40CNLb18ktPIbADQdaXdor3u5iF4Q5udkrXW" crossorigin="anonymous"></script>
	<!-- Vue Pagination -->
	<script src="https://unpkg.com/vuejs-paginate@2.1.0/dist/index.js" integrity="sha384-ZM/0jxdMKJriGW9zqYn4JH2/RJe77MGx7T119qRRO+fwQHDRdf93DP4oxwpJdBqb" crossorigin="anonymous"></script>
	<!-- Underscore -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js" integrity="sha256-G7A4JrJjJlFqP0yamznwPjAApIKPkadeHfyIwiaa9e0=" crossorigin="anonymous"></script>
	<!-- jQuery -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<!-- Fontawesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<style type="text/css">
		body {
			margin: 
			font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
			color: #aaa;
			font-size: 18px;
		}
		h1 {
			color: #719e40;
			letter-spacing: -3px;
			font-family: 'Lato', sans-serif;
			font-size: 50px;
			font-weight: 200;
			line-height: 1;
			margin-top: 40px;
			margin-bottom: 0;
		}
		h1 img {
			height: 1em;
			vertical-align: text-bottom;
		}
	</style>
</head>
<body>
	<div class="container">
		<h1 class="text-center">
			<img src="./../chronicle-logo.svg" />
			ChronicleX&nbsp; Explorer
		</h1>
		<div id="app">
			<small class="text-center">Client v0.0.1 - Server {{ version }}</small>
			<div class="row">
				<div class="col-md-4">
					<select v-model="instance" class="form-control custom-select">
						<option v-for="option in instances" :value="option.value">{{ option.label }}</option>
					</select>
				</div>
				<div class="col-md-8">
					<input class="form-control" type="text" value="" placeholder="Search by hash or summary hash..">
				</div>
			</div>
			<hr/>

			<div class="text-center" v-show="loading">
				<img src="./../loading.gif" />
			</div>

			<table v-show="!loading" class="table table-bordered">
				<tr class="text-center">
					<th>ID</th>
					<th>Blocks</th>
					<th>Created</th>
				</tr>
				<tr v-for="(block, index) in blocks">
					<td class="text-center"><h3>{{ index + 1 }}</h3></td>
					<td>
						<span v-if="!block.prev" class="badge badge-primary">
							<span class="fas fa-book"></span>
							Genesis Block
							<span class="fas fa-book"></span>
						</span>
						<span v-else class="badge badge-info">
							<small>
								<span class="fab fa-slack-hash"></span>
								<b>Previous Block</b>: {{ block.prev }}
							</small>
						</span>
						<details class="alert-secondary">
							<summary>Contents</summary>
							<p class="text-center">
								<div class="form-control">{{ block.contents }}</div>
							</p>
							<span class="badge badge-dark">
								<small>
									<span class="fas fa-file-contract"></span>
									<b>Signature</b>: {{ block.signature }}
								</small>
							</span>
							<br/>
							<span class="badge badge-dark">
								<small>
									<span class="fas fa-key"></span>
									<b>Public Key</b>: {{ block.publickey }}
								</small>
							</span>
							<span class="badge badge-dark">
								<small>
									<span class="fas fa-tint"></span>
									<b>Summary</b>: {{ block.summary }}
								</small>
							</span>
						</details>
						<span class="badge badge-warning">
							<small>
								<span class="fab fa-slack-hash"></span>
								<b>Block Hash</b>: {{ block.hash }}
							</small>
						</span>
					</td>
					<td class="text-center">
						<span class="badge badge-secondary">
							<small>
								<span class="fas fa-calendar-alt"></span>
								<b>{{ block.created }}
							</small>
						</span>
					</td>
				</tr>
			</table>

			<paginate
				v-show="!loading"
				:page-count="10"
				:container-class="pagination"
				:prev-text="prev"
				:next-text="next"
				:click-handler="clickCallback">
			</paginate>

		</div>
	</div>
	<script type="text/javascript">
		Vue.component('paginate', VuejsPaginate);
		var app = new Vue({
			el: '#app',
			data: {
				instance: '',
				page: 1,
				info: [],
				call: [],
				prev: 'Previous',
				next: 'Next',
				pagination: 'pagination',
				loading: true
			},
			computed: {
				origin(){
					return window.location.href.replace('/explorer', '');
				},
				version(){
					if(this.info){
						return 'v' + this.info.version;
					}
					return 'unknown';
				},
				pageCount(){
					if(this.info){
						if(this.info.meta){
							return this.info.meta.total_pages;
						}
					}
					return 0;
				},
				instances(){
					if(this.info){
						return _.map(this.info.results, function(item){
							var option = {label: 'Default Instance'};
							if(item.length <= 0){
								option.value = item;
							}else{
								option.label = option.value = item;
							}
							return option;
						});
					}
				},
				blocks(){
					if(this.call){
						return this.call.results;
					}
				}
			},
			methods: {
				getData(){
					axios.get(this.origin + '/export?instance=' + this.instance + '&page=' + this.page).then(
						response => {
							if(response.data){
								this.call = response.data;
							}
						}
					).finally(() => {this.loading = false});
				},
				clickCallback(){

				}
			},
			mounted(){
				axios.get(this.origin + '/instances').then(
					response => {
						if(response.data){
							this.info = response.data;
						}
					}
				).finally(() => { this.getData() });
			}
		});
	</script>
</body>
</html>
