<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="Chronicle is a software security project created by the PHP security and cryptography team at Paragon Initiative Enterprises, then Forked by Sudan Open Source Community under project name ChronicleX.">
        <meta name="keywords" content="Chronicle,ChronicleX,PHP 7,Slim,Sapient,Blakechain,sodium_compat,libsodium">
        <meta name="author" content="Sudan Open Source Community,Paragon Initiative Enterprises">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ChronicleX</title>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                line-height: 1;
                margin-bottom: 0;
            }
            h1 img {
                height: 1em;
                vertical-align: text-bottom;
            }

            hr {
                width: 75%;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
    </head>
    <body>
        <h1><img src="chronicle-logo.svg" />ChronicleX</h1>
        <p>
            Chronicle is a software security project created by
            <a target="_blank" href="https://paragonie.com">the PHP security and cryptography team at Paragon Initiative Enterprises</a>,
            <br/>then "Forked" by <a target="_blank" href="https://www.facebook.com/SudanOpenSourceCommunity">Sudan Open Source Community</a> under project name "<b>ChronicleX</b>".
        </p>
        <p>
            <a href="./chronicle">Click Here for the ChronicleX API</a>
        </p>
        <p>
            Please report any problems on <a target="_blank" href="https://github.com/SudanOpenSourceCommunity/chronicleX">Github</a>.
        </p>
        <hr />
        <p>Powered by
            <a target="_blank" href="https://secure.php.net">PHP 7</a>,
            <a target="_blank" href="http://www.slimframework.com">Slim</a>,
            <a target="_blank" href="https://github.com/paragonie/sapient">Sapient</a>,
            <a target="_blank" href="https://github.com/paragonie/blakechain">Blakechain</a>,
            <a target="_blank" href="https://github.com/paragonie/sodium_compat">sodium_compat</a>, and
            <a target="_blank" href="https://download.libsodium.org/doc/">libsodium</a>.
        </p>
    </body>
</html>
